version: "3.8"
services:
  # Quasar app service
  quasar-app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:80"

  # Nginx service to serve the Quasar app
  nginx:
    image: nginx:alpine
    ports:
      - "8080:80"
    volumes:
      - ./dist/spa:/usr/share/nginx/html
    depends_on:
      - quasar-app
